apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: mars-rover-navigation
resources:
- grpc-server.yaml
images:
- name: mars-rover-navigation
  newName: gcr.io/quiet-groove-373616/mars-rover-navigation
  newTag: 32171d6
